[profile.default]
solc = "0.8.25"
src = "contracts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/",
              "@uniswap/v2-core/contracts/=node_modules/@uniswap/v2-core/contracts",
              "@uniswap/v2-periphery/contracts/=node_modules/@uniswap/v2-periphery/contracts",
              "@uniswap/lib/contracts/=node_modules/@uniswap/lib/contracts",]

